var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                         o                           !xx                        ",
   "!!!!!!!!!!!!x        xxxxxxxxxxx                     !xxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxx              xxxx!    o  o             !xxxxxxxxxxxxxxxxxxxxxxxxxx",
   "  xxxxxxxxxxxxxxx          xxxx!   xxxxxx            !xxxxxxxxxxxxxxxxxxxxxx!!!!",
   "    xxxxxxxxx          o   xxxx!       x!   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!   ",
   "      xxxxxxx       xxxxxxxxxxx!       x!            !xxxxxxxxxxxxxxxxxx!!!     ",
   "!!!!!!xxxxxxx             xxxxx!       x!    o       !xxxxxxxxxxxxxxxx!!!       ",
   "xxxxxxxxxxxxxxxxxx        xxxxx!       xxxxxxxxxxx   !xxxxxxxxxxxxxx!!!        o",
   "xx                   o  o xxxxx!       x!            !xxxxxxxxxxxx!!!         xx",
   "xx                  xxxxxxxxxxx!       x!       o    !xxxxxxxxxx!!!         xxxx",
   "xx             o xxxxxxxxxxxxxx!       x!   xxxxxxxxxxxxxxxxxx!!!         xxxxxx",
   "xx            xxxxxxxxxxxxxxxxx!       x!                               xxxxxxxx",
   "xx  @   o  xxxxxxxxxxxxxxxxxxxx!  xxxxxx!    o              o  o      xxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!  xxxxxxxxxxxxxxxxxxxx     xxxxxx   xxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!xxxxxxxxxxxxxxxxxxxx xxx xxxxxx x xxxxxxxxxxxx",
   "                              x!!!x                  x!!x!!x    x!x!x           ",
   "                              x!!!x                  x!!x!!x    xxxxx           ",
   "                              x!!!x                  xxxxxxx                    ",
   "                              xxxxx                                             ",
   "                                                                               "],
  ["            x                     x                                                                       ",
   " www        x                     x k                                                                     ",
   " w w        x  o o                xxxxxxxxx                                                               ",
   " w@w        xxxxxxxxx                                                                                     ",
   "xxxxx       x                                  o                      ooooooooooooo                   o   ",
   "vvvvx       x                       xxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxx            xxxxxxxxxxx",
   "    x o     xxxxxxxxxxxxxxxxxxx                           x           x           x            x          ",
   "    xxx     x                 xxx                         x           x           x            x          ",
   "    x       x  o                xxx                       x!!!!!!!!!!!x           x!!!!!!!!!!!!x          ",
   "    x      =xxxxxxx     x         xxx                     x!!!!!!!!!!!x           x!!!!!!!!!!!!x          ",
   "    x       x           x           xxx                   xxxxxxxxxxxxx           x!!!!!!!!!!!!x          ",
   "    x     o x           x             xxx                                         x!!!!!!!!!!!!x          ",
   "    x     xxx       xxxxx               xxx                                       x!!!!!!!!!!!!x          ",
   "    x       x                                                                     x!!!!!!!!!!!!x          ",
   "    x =     xxxxxx                                                                xxxxxxxxxxxxxx          ",
   "    x       x             xxxxxxxxxxxxxxxxxxx xxx                                xxxxxxxxxxxxxxxx         ",
   "    x o     x       xxx                  o  x x!xxx                             xxxxxxxxxxxxxxxxxx        ",
   "    xxx     x       x xxx                   x x!!!xxx                           xxxxxxxxxxxxxxxxxx        ",
   "    x       x!!!!!!!x   xxx     xxxxxxxxxxxxx x!!!!!xxx                         xxxxxxxxxxxxxxxxxx        ",
   "    x      =x!!!!!!!x     xxx                 x!!!!!!!xxx                       xxxxxxxxxxxxxxxxxx        ",
   "    x       x!!!!!!!x       xxx               x!!!!!!!!!xxx                     xxxxxxxxxxxxxxxxxx        ",
   "    x     o x!!!!!!!x         xxx            oxxxxxxxxxxxxxxx                   xxxxxxxxxxxxxxxxxx        ",
   "    x     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx       xxxxxxxx                 xxxxxxxxxxxxxxxxxx        ",
   "    x       x          y           y                        xyxxx               xxxxxxxxxxxxxxxxxx        ",
   "    x =     x          y           y                         y  xxx             xxxxxxxxxxxxxxxxxx        ",
   "    x       x          y           y             o       o   y    xxx           xxxxxxxxxxxxxxxxxx        ",
   "    x       x                y     yyy    y     xxx y        y      xxx         xxxxxxxxxxxxxxxxxx        ",
   "    x              y         y          xxy    xx x y                           xxxxxxxxxxxxxxxxxx        ",
   "    x   o          y   o   x y     o      y   xx  x y    o                      xxxxxxxxxxxxxxxxxx        ",
   "    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        "],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                                                      ",
   "x                         y         y         x                                                                                                      ",
   "x k                                           x                                                                                                      ",
   "x       o                                     x                                                                                                      ",
   "xxxxxxxxx            y         y         y    x                                                                                                      ",
   "x               xxxxxxxxxxxxxxxxxxxxxxxxxxxx  x                                                                                                      ",
   "x            xxxx                          x  x                                                                                                      ",
   "x                                          x  x                                                                                                      ",
   "x                                         =x  x                                                                                                      ",
   "xxxxxxxxxxxxx                              x  x                                                                                                      ",
   "x           xxx                            x  x                                                                                                      ",
   "x             xxx       o o                x  x                                                                                                      ",
   "x               xxx                        x  x                                                                                                      ",
   "x                 xxxxxxxxxxxxxxxx         x  x                                                                                                      ",
   "x                  x                       x  x                                                                                                      ",
   "x=                                        =x  x                                                                                                      ",
   "x                  x                xxxxxxxx  x                                                                                                      ",
   "x!!!!!!!!!!!!!!!!!!xxxxxxxxx               x  x                                                                                                      ",
   "xxxxxxxxxxxxxxxxxxxxx      xxxx            x  x                                                                                                      ",
   "x!!!!!!!!!!!!!!!!!!!x         xxxx         x  x                                                                                                      ",
   "x                                x         x  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x                                xx        x  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x                                       xxxx  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x                                          x  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x                                 xx       x  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xo                                         x  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xx xx    xxx    xx  x          o      xxxxxx  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xx!xx!!!!xxx!!!!xx!!x        xxxxx         x  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxx xxx                  x  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x!!!!!!!!!!!!!!!!!!!x   xxxx               x  x              vxxxxxxxxxxxxxxxxxxxxxxxxxxxxxv  vxxxxxxxxxxxxxxxxxxxxxxxxxxxxxv                       x",
   "x                          xxx             x  x                 vxxxxxxxxxxxxxxxxxxxxxxxv        vxxxxxxxxxxxxxxxxxxxxxxxv                          x",
   "x                            xxxxxx        x  x                    vxxxxxxxxxxxxxxxxxv              vxxxxxxxxxxxxxxxxxv                   o         x",
   "x                                 xxx      x  x                       vxxxxxxxxxxxv                    vxxxxxxxxxxxv                      x         x",
   "x                                          x  x                          vxxxxxv                          vxxxxxv                        xxx        x",
   "xo   xxx                                 xxx  x                             v                                v                          xxxxx       x",
   "xxxx   xx    xx   xxxx     xxxx    o       x  x                                                                                        xxxxxxx      x",
   "x                                xxxxx     x  x w                                                                                     xxxxxxxxx     x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x         x  x                                                                                      xxxxxxxxxxx    x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx      xxxx  xxxxx                                                                                 xxxxxxxxxxxxx   x",
   "x                                                                                                                                  xxxxxxxxxxxxxxx  x",
   "x   www                                                     o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o xxxxxxxxxxxxxxxxx x",
   "x   w w                xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x   w@w         o    xxx                                                                                                                             ",
   "xxxxxxxxxxxxxxxxxxxxxx                                                                                                                               "],
  ["                                                                                                        ",
   "                                                                                                        ",
   "                                                                                                        ",
   "                                                                                                        ",
   "     xx         xx   xxxxxxxx  xx    xx    xx               x               xx  xx  xx       xx   xx    ",
   "      xx       xx    xxxxxxxx  xx    xx     xx             xxx             xx   xx  xxx      xx   xx    ",
   "       xx     xx     xx    xx  xx    xx      xx           xx xx           xx    xx  xxxx     xx   xx    ",
   "        xx   xx      xx    xx  xx    xx       xx         xx   xx         xx     xx  xxxxx    xx   xx    ",
   "         xx xx       xx    xx  xx    xx        xx       xx     xx       xx      xx  xx xxx   xx   xx    ",
   "          xxx        xx    xx  xx    xx         xx     xx       xx     xx       xx  xx  xxx  xx   xx    ",
   "          xxx        xx    xx  xx    xx          xx   xx         xx   xx        xx  xx   xxx xx         ",
   "          xxx        xxxxxxxx  xxxxxxxx           xx xx           xx xx         xx  xx    xxxxx   xx    ",
   "          xxx        xxxxxxxx  xxxxxxxx            xxx             xxx          xx  xx     xxxx   xx    ",
   "          k k                                                                                           ",
   "          k@k                                                                                           ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                                                                        ",
   "                                                                                                        ",
   "                                                                                                        "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
